### ISSUE TITLE
add link to github

### ISSUE THREAD

**Issue by fonsp** [mitmath/18S191#5] opened 2020-09-02 21:56 UTC
Which GitHub do you mean? The website?

**Comment by tasneemkoushar** [comment] 2020-09-04 06:10
The issue is not clear to me! Can you tell us more about the issue?

**Comment by fonsp** [comment] 2020-09-04 13:41
I'm sorry that was a useless issue 😬

I meant that the web pages should like back to GitHub, inviting readers to contribute a fix or open an issue if they find something.

**Comment by dpsanders** [comment] 2020-09-04 13:53
Yes definitely a good idea!

**Comment by fonsp** [comment] 2020-09-04 14:05
@shashi is this trivial for you to do? Otherwise I will look into it myself

**Comment by shashi** [comment] 2020-09-04 14:08
Like edit on github link on each page??

I don't know how to do that off the top of my head, but I'm sure it's not that hard!

**Comment by tasneemkoushar** [comment] 2020-09-04 14:31
I will do it, kindly assign this issue to me. Thank you

**Comment by dpsanders** [comment] 2020-09-05 17:51
Fixed by #11

**Closed** 2020-09-05 17:52 UTC
