### ISSUE TITLE
Symbolic expansion broken in Newton notebook 1.6

### ISSUE THREAD

**Issue by dpsanders** [mitmath/18S191#115] opened 2021-10-21 17:35 UTC
@fonsp: Symbolic expansion isn't working on the published version. Maybe it just needs regenerating with a current version of Symbolics.jl?

**Comment by fonsp** [comment] 2021-10-26 10:44
@dpsanders Do you mean that we are using a version of Symbolics where it doesn't work, but it has been fixed in a recent version?

**Comment by fonsp** [comment] 2024-08-10 14:30
The issue is that `expand` has no effect

<img width="467" alt="image" src="https://github.com/user-attachments/assets/6b3d5b11-598d-4c73-8661-608b1f4fb909">


in https://computationalthinking.mit.edu/Fall24/images_abstractions/newton_method/

**Closed as completed** 2024-08-10 14:38 UTC
